"""Added Admin table

Revision ID: 28b4543fe5f1
Revises: 546e26d721d6
Create Date: 2026-02-21 14:42:53.548821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28b4543fe5f1'
down_revision = '546e26d721d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('AdminID', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('AdminID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('Author',
    sa.Column('AuthorID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Biography', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('AuthorID')
    )
    op.create_table('Book',
    sa.Column('ISBN', sa.String(length=20), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('StockQuantity', sa.Integer(), nullable=True),
    sa.Column('Format', sa.Enum('Physical', 'eBook'), nullable=False),
    sa.Column('PublicationDate', sa.Date(), nullable=True),
    sa.Column('CoverImageURL', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ISBN')
    )
    op.create_table('Category',
    sa.Column('CategoryID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('CategoryID')
    )
    op.create_table('User',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Address', sa.Text(), nullable=True),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('BookAuthor',
    sa.Column('ISBN', sa.String(length=20), nullable=False),
    sa.Column('AuthorID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AuthorID'], ['Author.AuthorID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ISBN'], ['Book.ISBN'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ISBN', 'AuthorID')
    )
    op.create_table('BookCategory',
    sa.Column('ISBN', sa.String(length=20), nullable=False),
    sa.Column('CategoryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CategoryID'], ['Category.CategoryID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ISBN'], ['Book.ISBN'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ISBN', 'CategoryID')
    )
    op.create_table('Order',
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('OrderDate', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('TotalAmount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ShippingAddress', sa.Text(), nullable=True),
    sa.Column('OrderStatus', sa.Enum('Pending', 'Shipped', 'Delivered', 'Cancelled'), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_table('OrderItem',
    sa.Column('OrderItemID', sa.Integer(), nullable=False),
    sa.Column('OrderID', sa.Integer(), nullable=True),
    sa.Column('ISBN', sa.String(length=20), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('UnitPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ISBN'], ['Book.ISBN'], ),
    sa.ForeignKeyConstraint(['OrderID'], ['Order.OrderID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('OrderItemID')
    )
    op.create_table('Payment',
    sa.Column('PaymentID', sa.Integer(), nullable=False),
    sa.Column('OrderID', sa.Integer(), nullable=True),
    sa.Column('PaymentMethod', sa.String(length=50), nullable=True),
    sa.Column('TransactionID', sa.String(length=100), nullable=True),
    sa.Column('PaymentStatus', sa.Enum('Success', 'Failed', 'Pending'), nullable=True),
    sa.Column('PaymentDate', sa.DateTime(), nullable=True),
    sa.Column('Amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['OrderID'], ['Order.OrderID'], ),
    sa.PrimaryKeyConstraint('PaymentID'),
    sa.UniqueConstraint('TransactionID')
    )
    op.create_table('DigitalDownload',
    sa.Column('DownloadID', sa.Integer(), nullable=False),
    sa.Column('OrderItemID', sa.Integer(), nullable=True),
    sa.Column('DownloadLink', sa.String(length=255), nullable=True),
    sa.Column('ExpiryDate', sa.DateTime(), nullable=True),
    sa.Column('AccessCount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['OrderItemID'], ['OrderItem.OrderItemID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('DownloadID')
    )
    op.drop_table('orderitem')
    op.drop_table('order')
    op.drop_table('bookcategory')
    op.drop_table('author')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('OrderID'))
        batch_op.drop_index(batch_op.f('TransactionID'))

    op.drop_table('payment')
    op.drop_table('bookauthor')
    op.drop_table('digitaldownload')
    op.drop_table('book')
    op.drop_table('category')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Email'))

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('UserID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Address', mysql.TEXT(), nullable=True),
    sa.Column('Phone', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Email'), ['Email'], unique=True)

    op.create_table('category',
    sa.Column('CategoryID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('CategoryID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('book',
    sa.Column('ISBN', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Description', mysql.TEXT(), nullable=True),
    sa.Column('Price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('StockQuantity', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('Format', mysql.ENUM('Physical', 'eBook'), nullable=False),
    sa.Column('PublicationDate', sa.DATE(), nullable=True),
    sa.Column('CoverImageURL', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ISBN'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('digitaldownload',
    sa.Column('DownloadID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('OrderItemID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('DownloadLink', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ExpiryDate', mysql.DATETIME(), nullable=True),
    sa.Column('AccessCount', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['OrderItemID'], ['orderitem.OrderItemID'], name=op.f('digitaldownload_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('DownloadID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bookauthor',
    sa.Column('ISBN', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('AuthorID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['AuthorID'], ['author.AuthorID'], name=op.f('bookauthor_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ISBN'], ['book.ISBN'], name=op.f('bookauthor_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ISBN', 'AuthorID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payment',
    sa.Column('PaymentID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('OrderID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('PaymentMethod', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('TransactionID', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('PaymentStatus', mysql.ENUM('Success', 'Failed', 'Pending'), nullable=True),
    sa.Column('PaymentDate', mysql.DATETIME(), nullable=True),
    sa.Column('Amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['OrderID'], ['order.OrderID'], name=op.f('payment_ibfk_1')),
    sa.PrimaryKeyConstraint('PaymentID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('TransactionID'), ['TransactionID'], unique=True)
        batch_op.create_index(batch_op.f('OrderID'), ['OrderID'], unique=True)

    op.create_table('author',
    sa.Column('AuthorID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Biography', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('AuthorID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bookcategory',
    sa.Column('ISBN', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('CategoryID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['CategoryID'], ['category.CategoryID'], name=op.f('bookcategory_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ISBN'], ['book.ISBN'], name=op.f('bookcategory_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ISBN', 'CategoryID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('order',
    sa.Column('OrderID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('OrderDate', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('TotalAmount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('ShippingAddress', mysql.TEXT(), nullable=True),
    sa.Column('OrderStatus', mysql.ENUM('Pending', 'Shipped', 'Delivered', 'Cancelled'), server_default=sa.text("'Pending'"), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], name=op.f('order_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('OrderID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orderitem',
    sa.Column('OrderItemID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('OrderID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ISBN', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('UnitPrice', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ISBN'], ['book.ISBN'], name=op.f('orderitem_ibfk_2')),
    sa.ForeignKeyConstraint(['OrderID'], ['order.OrderID'], name=op.f('orderitem_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('OrderItemID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('DigitalDownload')
    op.drop_table('Payment')
    op.drop_table('OrderItem')
    op.drop_table('Order')
    op.drop_table('BookCategory')
    op.drop_table('BookAuthor')
    op.drop_table('User')
    op.drop_table('Category')
    op.drop_table('Book')
    op.drop_table('Author')
    op.drop_table('Admin')
    # ### end Alembic commands ###
