"""Initial clean migration with lowercase schema and BookID

Revision ID: b7ca01a0811d
Revises: 
Create Date: 2026-02-21 15:52:15.550538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ca01a0811d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('AdminID', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('AdminID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('author',
    sa.Column('AuthorID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Biography', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('AuthorID')
    )
    op.create_table('book',
    sa.Column('BookID', sa.Integer(), nullable=False),
    sa.Column('ISBN', sa.String(length=20), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('StockQuantity', sa.Integer(), nullable=True),
    sa.Column('Format', sa.Enum('Physical', 'eBook'), nullable=False),
    sa.Column('PublicationDate', sa.Date(), nullable=True),
    sa.Column('CoverImageURL', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('BookID'),
    sa.UniqueConstraint('ISBN')
    )
    op.create_table('category',
    sa.Column('CategoryID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('CategoryID')
    )
    op.create_table('user',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Address', sa.Text(), nullable=True),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('bookauthor',
    sa.Column('BookID', sa.Integer(), nullable=False),
    sa.Column('AuthorID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AuthorID'], ['author.AuthorID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['BookID'], ['book.BookID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('BookID', 'AuthorID')
    )
    op.create_table('bookcategory',
    sa.Column('BookID', sa.Integer(), nullable=False),
    sa.Column('CategoryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['BookID'], ['book.BookID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['CategoryID'], ['category.CategoryID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('BookID', 'CategoryID')
    )
    op.create_table('order',
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('OrderDate', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('TotalAmount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ShippingAddress', sa.Text(), nullable=True),
    sa.Column('OrderStatus', sa.Enum('Pending', 'Shipped', 'Delivered', 'Cancelled'), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_table('orderitem',
    sa.Column('OrderItemID', sa.Integer(), nullable=False),
    sa.Column('OrderID', sa.Integer(), nullable=True),
    sa.Column('BookID', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('UnitPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['BookID'], ['book.BookID'], ),
    sa.ForeignKeyConstraint(['OrderID'], ['order.OrderID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('OrderItemID')
    )
    op.create_table('payment',
    sa.Column('PaymentID', sa.Integer(), nullable=False),
    sa.Column('OrderID', sa.Integer(), nullable=True),
    sa.Column('PaymentMethod', sa.String(length=50), nullable=True),
    sa.Column('TransactionID', sa.String(length=100), nullable=True),
    sa.Column('PaymentStatus', sa.Enum('Success', 'Failed', 'Pending'), nullable=True),
    sa.Column('PaymentDate', sa.DateTime(), nullable=True),
    sa.Column('Amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['OrderID'], ['order.OrderID'], ),
    sa.PrimaryKeyConstraint('PaymentID'),
    sa.UniqueConstraint('TransactionID')
    )
    op.create_table('digitaldownload',
    sa.Column('DownloadID', sa.Integer(), nullable=False),
    sa.Column('OrderItemID', sa.Integer(), nullable=True),
    sa.Column('DownloadLink', sa.String(length=255), nullable=True),
    sa.Column('ExpiryDate', sa.DateTime(), nullable=True),
    sa.Column('AccessCount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['OrderItemID'], ['orderitem.OrderItemID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('DownloadID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digitaldownload')
    op.drop_table('payment')
    op.drop_table('orderitem')
    op.drop_table('order')
    op.drop_table('bookcategory')
    op.drop_table('bookauthor')
    op.drop_table('user')
    op.drop_table('category')
    op.drop_table('book')
    op.drop_table('author')
    op.drop_table('admin')
    # ### end Alembic commands ###
