"""Added Cart and CartItem models

Revision ID: b83ff9af7c3a
Revises: f4dd487ba82f
Create Date: 2026-03-14 13:02:03.924799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83ff9af7c3a'
down_revision = 'f4dd487ba82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('CartID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CartID'),
    sa.UniqueConstraint('UserID')
    )
    op.create_table('cartitem',
    sa.Column('CartItemID', sa.Integer(), nullable=False),
    sa.Column('CartID', sa.Integer(), nullable=True),
    sa.Column('BookID', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['BookID'], ['book.BookID'], ),
    sa.ForeignKeyConstraint(['CartID'], ['cart.CartID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CartItemID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartitem')
    op.drop_table('cart')
    # ### end Alembic commands ###
