"""Add address and phone to admin

Revision ID: f4dd487ba82f
Revises: b7ca01a0811d
Create Date: 2026-02-28 14:52:14.394439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4dd487ba82f'
down_revision = 'b7ca01a0811d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('Phone')
        batch_op.drop_column('Address')

    # ### end Alembic commands ###
